name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci.yml'
      - '__stories__/**'
      - '__tests__/**'
      - '.storybook/**'
      - '.lintstagedrc.json'
      - '.oxfmtrc.json'
      - '.oxlintrc.json'
      - '.prettierrc.json'
      - 'src/**'
      - 'eslint.config.ts'
      - 'package.json'
      - 'package-lock.json'
      - 'tsdown.config.ts'
      - 'tsconfig.json'
      - 'vitest.config.ts'
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/ci.yml'
      - '__stories__/**'
      - '__tests__/**'
      - '.storybook/**'
      - '.lintstagedrc.json'
      - '.oxfmtrc.json'
      - '.oxlintrc.json'
      - '.prettierrc.json'
      - 'src/**'
      - 'eslint.config.ts'
      - 'package.json'
      - 'package-lock.json'
      - 'tsdown.config.ts'
      - 'tsconfig.json'
      - 'vitest.config.ts'
jobs:
  testing:
    name: Testing and Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout project code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Use Node.js LTS
        uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: lts/*
      - name: Installation
        run: npm ci
      - name: Check
        run: npm run check
